### ISSUE TITLE
Cannot convert "6:24 - Danger" (map#6fc6) even though it is standard mode

### ISSUE THREAD

**Issue by laundmo** [CodeStix/Beat-360fyer#1]
hello there,

first off: your tool works great for what ive tried, and tho i can tell its automatically converting, the maps are playable.

when trying to convert some of my songs thouh, i noticed that the conversion fails for a few songs even though they have standard mode, im overwriting existing 360, and im running in Administrator mode.

The beatmap i was using can be found here: https://bsaber.com/songs/6fc6/

Ive tried renaming the .dat files from "EasyStandard.dat" to "Easy.dat" an changing the "_beatmapFilname" in the info.dat, but that didnt work either. (i was assuming a issue with names, since maps where it worked had those )

Ive also tried removing the "Lightshow" difficulty to no avail.

**Comment by CodeStix** [comment]
There was a problem with JSON serialization, it expected an array, but an object was given. This is fixed in the next version. Detailed error messages will be added too, instead of a 'whoops try this'. I converted your map, so you don't have to wait until next release:
[danger.zip](https://github.com/CodeStix/Beat-360fyer/files/3990795/danger.zip)

**Comment by laundmo** [comment]
good to know you're on it, thanks
